/* CONSTRAINT : 제약조건 */
CREATE TABLE project.DEPT
( DEPTNO int, 
	DNAME VARCHAR(14), 
	LOC VARCHAR(13), 
	CONSTRAINT PK_DEPT PRIMARY KEY (DEPTNO)
);

CREATE TABLE project.EMP 
( EMPNO int, 
	ENAME VARCHAR(10), 
	JOB VARCHAR(9), 
	MGR int, 
	HIREDATE DATE, 
	SAL int, 
	COMM int, 
	DEPTNO int, 
	CONSTRAINT PK_EMP PRIMARY KEY (EMPNO),
	CONSTRAINT FK_DEPTNO FOREIGN KEY (DEPTNO) REFERENCES project.DEPT (DEPTNO)
);
